export default {
  lang: "en",
  prefix: "",
  labels: {
    language: "Language",
    primaryNavigation: "Primary navigation",
    footerNavigation: "Footer navigation",
    products: "Products",
    about: "About",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Contact",
    home: "Home",
    rights: "All rights reserved.",
  },
  meta: {
    title: "JAM Daily Tools | Practical apps for everyday work",
    description: "JAM Daily Tools LLC is an independent software studio building focused apps for everyday work, including TourneySmith for racket-sport tournaments.",
  },
  landing: {
    heading: "Focused software for<br><span class=\"grad\">real work.</span>",
    lede: "We build clear, dependable apps for recurring tasks, starting with tournament organization.",
    viewApps: "View our apps",
    getInTouch: "Get in touch",
    workTitle: "How we work",
    workIntro: "Each product starts with a specific job and stays focused on doing it well.",
    values: [
      {title: "Useful by design", body: "We begin with the work people actually need to complete and remove steps that do not help."},
      {title: "Clear about data", body: "Each product explains what it collects, why it needs it, and which controls are available."},
      {title: "Built for both platforms", body: "Our mobile products are designed for Android and iOS with shared behavior across both."},
    ],
    appsTitle: "Our apps",
    appsIntro: "The first product from JAM Daily Tools LLC.",
    comingSoon: "Coming soon",
    productTagline: "Craft of running tournaments.",
    productBody: "TourneySmith helps racket-sport organizers choose a format, manage players and groups, schedule venues and courts, share invitations, and keep live brackets, scores, standings, and results together. It supports padel, tennis, pickleball, badminton, squash, racquetball, and table tennis.",
    visitProduct: "Visit TourneySmith",
    aboutBody: "JAM Daily Tools LLC is an independent software studio based in Texas. We develop and publish focused tools, beginning with TourneySmith for racket-sport tournament organizers.",
    contactIntro: "Use the address that matches your question.",
    general: "Company and business",
    appSupport: "Product support",
  },
  privacy: {
    metaTitle: "Website Privacy Policy | JAM Daily Tools",
    metaDescription: "Privacy policy for the JAM Daily Tools company website, including Cloudflare request data, language preferences, email correspondence, retention, and privacy requests.",
    title: "Website Privacy Policy",
    updated: "Last updated: September 27, 2026. Document version: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Scope", body: `<p>This policy covers <strong>jamdailytools.com</strong>, the public company website of JAM Daily Tools LLC. The website provides company and product information. It has no user accounts, payment form, or product database.</p><p>It does not govern the TourneySmith app, invitation service, or product account data. Those are covered by the localized <a data-product-link href="https://tourneysmith.com/privacy">TourneySmith Privacy Policy</a>.</p>`},
      {id: "controller", title: "2. Company and contact", body: `<p>JAM Daily Tools LLC is responsible for the website information described here.</p><address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>United States</address><p>Privacy questions: <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. General inquiries: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>. For Canadian and Québec inquiries, the responsible title is <strong>Privacy Officer</strong>.</p>`},
      {id: "website-data", title: "3. Website request information", body: `<p>We do not add analytics, advertising, profiling, or social-media tracking scripts to this website. Cloudflare automatically processes ordinary request data such as IP address, browser and device information, requested path, time, security signals, and diagnostic logs to deliver the static files, route traffic, and protect the website from abuse.</p>`},
      {id: "language-preference", title: "4. Language preference", body: `<p>If you choose a language, the site stores the value in your browser under <code>jam-language</code>. The marketing landing page can also use your browser’s language setting to suggest a localized page. Privacy and Terms pages never redirect automatically by language. This preference is not used for analytics or advertising and can be removed by clearing site storage.</p>`},
      {id: "email", title: "5. If you email us", body: `<p>When you email an address on this site, we receive your address, message, attachments, and related delivery metadata. We use them to respond, provide support, keep appropriate business records, protect our systems, and meet legal duties. Do not send passwords or sensitive documents unless we provide a secure method.</p>`},
      {id: "cloudflare", title: "6. Hosting provider", body: `<p>The website is delivered through Cloudflare Workers Static Assets, DNS, and security services. Cloudflare processes request information under its applicable terms and privacy policy. Links to TourneySmith, app stores, and other external sites are governed by those sites’ notices.</p>`},
      {id: "sharing", title: "7. Sharing", body: `<p>We do not sell website visitor information and do not share it for targeted advertising. We may disclose email correspondence to service providers that help us operate email or business systems, to professional advisers under confidentiality, to authorities where legally required, or in a corporate transaction with appropriate protections.</p>`},
      {id: "retention", title: "8. Retention", body: `<p>The browser language preference remains until you change it or clear site storage. Cloudflare retains technical records according to its configured services and contractual terms. We keep correspondence only as long as reasonably needed for the inquiry, security, business records, dispute resolution, and legal obligations, then delete or anonymize it when practical.</p>`},
      {id: "rights", title: "9. Your choices and rights", body: `<p>Depending on where you live, you may request access, correction, deletion, portability, restriction, objection, information about disclosures, or withdrawal of consent for personal information held by JAM Daily Tools LLC. Email <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. We may verify your identity. You may also complain to the privacy regulator available in your jurisdiction, including the Office of the Privacy Commissioner of Canada or Québec’s Commission d’accès à l’information where applicable.</p>`},
      {id: "children", title: "10. Children", body: `<p>This company website is not directed to children and does not knowingly request their personal information. Contact us if you believe a child sent information through email without appropriate authorization.</p>`},
      {id: "international", title: "11. International processing", body: `<p>JAM Daily Tools LLC is in the United States. Cloudflare and email providers may process technical or correspondence information in the United States and other countries under their applicable terms. Privacy rules can differ between countries. Mandatory Canadian, Québec, Brazilian, Mexican, and other local rights remain available when they apply.</p>`},
      {id: "changes", title: "12. Changes", body: `<p>We may update this policy. We will post the revised date and document version here and provide additional notice when required.</p>`},
      {id: "contact", title: "13. Contact", body: `<p>Email <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a> or write to the company address in section 2.</p>`},
    ],
  },
  terms: {
    metaTitle: "Website Terms of Use | JAM Daily Tools",
    metaDescription: "Terms for using the JAM Daily Tools company website, with a clear boundary between this informational site and the separate TourneySmith app and service.",
    title: "Website Terms of Use",
    updated: "Effective and last updated: September 27, 2026. Document version: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Scope", body: `<p>These Terms govern your use of <strong>jamdailytools.com</strong>, the informational company website of JAM Daily Tools LLC. By using the site, you agree to these Terms. If you do not agree, do not use the site.</p>`},
      {id: "app-boundary", title: "2. Our apps use separate terms", body: `<p>These Website Terms do not govern TourneySmith accounts, tournaments, purchases, invitations, or app data. TourneySmith has separate localized <a data-product-link href="https://tourneysmith.com/terms">Terms of Service</a> and a <a data-product-link href="https://tourneysmith.com/privacy">Privacy Policy</a>. Nothing on this company website changes those product terms.</p>`},
      {id: "site-use", title: "3. Permitted use", body: `<p>You may view and share public pages for lawful personal or business evaluation. Do not interfere with the site, attempt unauthorized access, introduce harmful code, scrape it in a way that burdens the service, misrepresent our content, or use it to violate the law.</p>`},
      {id: "intellectual-property", title: "4. Intellectual property", body: `<p>The website’s text, design, logos, product names, and other content belong to JAM Daily Tools LLC or its licensors. You may not reproduce or use them commercially without permission, except as allowed by law. No trademark or software license is granted.</p>`},
      {id: "third-party-links", title: "5. Third-party links", body: `<p>The site links to product sites, app stores, email services, and other third parties. We do not control their availability, content, security, terms, or privacy practices. A link does not by itself endorse every statement or offering on the destination.</p>`},
      {id: "warranty", title: "6. Disclaimer", body: `<p>To the fullest extent permitted by law, the website is provided “as is” and “as available.” We do not guarantee uninterrupted access, freedom from errors, or that product descriptions remain current at every moment. Nothing excludes a warranty or consumer guarantee that cannot lawfully be excluded.</p>`},
      {id: "liability", title: "7. Limitation of liability", body: `<p>To the fullest extent permitted by law, JAM Daily Tools LLC is not liable for indirect, incidental, special, consequential, exemplary, or punitive loss arising from use of this website. This limitation does not apply to liability that cannot legally be limited.</p>`},
      {id: "mandatory-rights", title: "8. Mandatory consumer rights", body: `<p>Nothing in these Terms limits non-waivable rights under applicable U.S., Brazilian, Mexican, Canadian, Québec, or other consumer law. A mandatory local rule prevails over an inconsistent provision only to the extent required.</p>`},
      {id: "governing-law", title: "9. Governing law", body: `<p>Texas law governs these Terms without regard to conflict-of-law rules, except that mandatory law in your place of residence remains protected. Courts with jurisdiction in Bexar County, Texas are the agreed forum where the law permits that choice. These Terms do not require arbitration or waive a legally available class proceeding.</p>`},
      {id: "changes", title: "10. Changes", body: `<p>We may update these Terms by posting a new date and document version. Changes apply prospectively. Continued use after an effective update means you accept the revised Website Terms where permitted by law.</p>`},
      {id: "contact", title: "11. Contact", body: `<address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>United States</address><p>Email <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>.</p>`},
    ],
  },
};
