export default {
  lang: "es",
  prefix: "es/",
  labels: {
    language: "Idioma",
    primaryNavigation: "Navegación principal",
    footerNavigation: "Navegación del pie de página",
    products: "Productos",
    about: "Nosotros",
    privacy: "Privacidad",
    terms: "Términos",
    contact: "Contacto",
    home: "Inicio",
    rights: "Todos los derechos reservados.",
  },
  meta: {
    title: "JAM Daily Tools | Aplicaciones prácticas para el trabajo diario",
    description: "JAM Daily Tools LLC es un estudio de software independiente que crea aplicaciones enfocadas en tareas cotidianas, como TourneySmith para torneos de deportes de raqueta.",
  },
  landing: {
    heading: "Software enfocado para<br><span class=\"grad\">el trabajo real.</span>",
    lede: "Creamos aplicaciones claras y confiables para tareas frecuentes, empezando por la organización de torneos.",
    viewApps: "Ver aplicaciones",
    getInTouch: "Escríbenos",
    workTitle: "Cómo trabajamos",
    workIntro: "Cada producto parte de una tarea concreta y se concentra en resolverla bien.",
    values: [
      {title: "Útil desde el diseño", body: "Empezamos por el trabajo que las personas realmente necesitan completar y quitamos pasos que no ayudan."},
      {title: "Claridad sobre los datos", body: "Cada producto explica qué recopila, por qué lo necesita y qué controles ofrece."},
      {title: "Hecho para ambas plataformas", body: "Diseñamos nuestros productos móviles para Android y iOS con un comportamiento compartido."},
    ],
    appsTitle: "Nuestras aplicaciones",
    appsIntro: "El primer producto de JAM Daily Tools LLC.",
    comingSoon: "Próximamente",
    productTagline: "El arte de organizar torneos.",
    productBody: "TourneySmith ayuda a organizadores de deportes de raqueta a elegir el formato, administrar jugadores y grupos, programar sedes y canchas, compartir invitaciones y reunir cuadros en vivo, marcadores, posiciones y resultados. Admite pádel, tenis, pickleball, bádminton, squash, racquetball y tenis de mesa.",
    visitProduct: "Visitar TourneySmith",
    aboutBody: "JAM Daily Tools LLC es un estudio de software independiente con sede en Texas. Desarrollamos y publicamos herramientas enfocadas, comenzando por TourneySmith para organizadores de torneos de deportes de raqueta.",
    contactIntro: "Usa la dirección que corresponda a tu pregunta.",
    general: "Empresa y negocios",
    appSupport: "Soporte del producto",
  },
  privacy: {
    metaTitle: "Política de Privacidad del Sitio | JAM Daily Tools",
    metaDescription: "Política de privacidad del sitio corporativo de JAM Daily Tools, incluidos datos técnicos de Cloudflare, preferencia de idioma, correos, conservación y solicitudes.",
    title: "Política de Privacidad del Sitio Web",
    updated: "Última actualización: 27 de septiembre de 2026. Versión del documento: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Alcance", body: `<p>Esta política cubre <strong>jamdailytools.com</strong>, el sitio corporativo público de JAM Daily Tools LLC. Presenta información sobre la empresa y sus productos. No tiene cuentas, formulario de pago ni base de datos de productos.</p><p>No regula la aplicación TourneySmith, las invitaciones ni los datos de sus cuentas. Eso se rige por la <a data-product-link href="https://tourneysmith.com/es/privacy">Política de Privacidad de TourneySmith</a>.</p>`},
      {id: "controller", title: "2. Empresa y contacto", body: `<p>JAM Daily Tools LLC es responsable de la información del sitio descrita aquí.</p><address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>Estados Unidos</address><p>Privacidad: <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Consultas generales: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>. Para Canadá y Québec, el cargo responsable es <strong>Responsable de Privacidad</strong>.</p>`},
      {id: "website-data", title: "3. Datos técnicos del sitio", body: `<p>No añadimos scripts de analítica, publicidad, perfiles ni seguimiento social. Cloudflare procesa automáticamente datos habituales como dirección IP, navegador, dispositivo, ruta solicitada, hora, señales de seguridad y registros de diagnóstico para entregar los archivos, dirigir el tráfico y proteger el sitio.</p>`},
      {id: "language-preference", title: "4. Preferencia de idioma", body: `<p>Si eliges un idioma, el sitio guarda <code>jam-language</code> en tu navegador. La página promocional también puede usar el idioma del navegador para sugerir una versión. Las páginas de Privacidad y Términos nunca cambian automáticamente de idioma. La preferencia no se usa para analítica o publicidad y puedes borrarla al limpiar los datos del sitio.</p>`},
      {id: "email", title: "5. Si nos envías un correo", body: `<p>Recibimos tu dirección, mensaje, archivos adjuntos y metadatos de entrega. Los usamos para responder, dar soporte, conservar registros empresariales apropiados, proteger sistemas y cumplir la ley. No envíes contraseñas ni documentos sensibles salvo que ofrezcamos un método seguro.</p>`},
      {id: "cloudflare", title: "6. Proveedor de alojamiento", body: `<p>El sitio se entrega mediante Cloudflare Workers Static Assets, DNS y servicios de seguridad. Cloudflare procesa datos técnicos según sus términos y política. Los enlaces a TourneySmith, tiendas y otros sitios se rigen por sus propios avisos.</p>`},
      {id: "sharing", title: "7. Intercambio", body: `<p>No vendemos datos de visitantes ni los compartimos para publicidad dirigida. Podemos comunicar correos a proveedores de nuestros sistemas, asesores sujetos a confidencialidad, autoridades cuando la ley lo exige o en una operación corporativa con protecciones adecuadas.</p>`},
      {id: "retention", title: "8. Conservación", body: `<p>La preferencia de idioma permanece hasta que la cambies o borres los datos. Cloudflare conserva registros técnicos según su configuración y contratos. Conservamos correspondencia solo durante el tiempo razonablemente necesario para la consulta, seguridad, registros, controversias y obligaciones legales, y después la eliminamos o anonimizamos cuando sea posible.</p>`},
      {id: "rights", title: "9. Opciones y derechos", body: `<p>Según tu residencia, puedes solicitar acceso, rectificación, eliminación, portabilidad, limitación, oposición, información sobre destinatarios o retiro del consentimiento respecto de datos en poder de JAM Daily Tools LLC. Escribe a <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Podemos verificar tu identidad. También puedes reclamar ante la autoridad competente, incluida la Office of the Privacy Commissioner of Canada o la Commission d’accès à l’information de Québec cuando corresponda.</p>`},
      {id: "children", title: "10. Menores", body: `<p>Este sitio corporativo no está dirigido a menores ni solicita intencionalmente sus datos. Avísanos si crees que un menor envió información por correo sin autorización adecuada.</p>`},
      {id: "international", title: "11. Tratamiento internacional", body: `<p>JAM Daily Tools LLC está en Estados Unidos. Cloudflare y los proveedores de correo pueden procesar datos técnicos o correspondencia en Estados Unidos y otros países conforme a sus términos. Las reglas pueden variar. Se conservan los derechos obligatorios de Canadá, Québec, Brasil, México y otras jurisdicciones cuando correspondan.</p>`},
      {id: "changes", title: "12. Cambios", body: `<p>Podemos actualizar la política. Publicaremos aquí la nueva fecha y versión y daremos aviso adicional cuando sea obligatorio.</p>`},
      {id: "contact", title: "13. Contacto", body: `<p>Escribe a <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a> o al domicilio de la sección 2.</p>`},
    ],
  },
  terms: {
    metaTitle: "Términos de Uso del Sitio | JAM Daily Tools",
    metaDescription: "Términos para usar el sitio corporativo de JAM Daily Tools, con una separación clara entre este sitio informativo y la aplicación TourneySmith.",
    title: "Términos de Uso del Sitio Web",
    updated: "Vigentes y actualizados el 27 de septiembre de 2026. Versión: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Alcance", body: `<p>Estos Términos regulan el uso de <strong>jamdailytools.com</strong>, sitio informativo de JAM Daily Tools LLC. Al usarlo, los aceptas. Si no estás de acuerdo, no uses el sitio.</p>`},
      {id: "app-boundary", title: "2. Las aplicaciones tienen términos propios", body: `<p>Estos Términos no regulan cuentas, torneos, compras, invitaciones ni datos de TourneySmith. El producto tiene <a data-product-link href="https://tourneysmith.com/es/terms">Términos de Servicio</a> y <a data-product-link href="https://tourneysmith.com/es/privacy">Política de Privacidad</a> propios. Nada en este sitio corporativo los modifica.</p>`},
      {id: "site-use", title: "3. Uso permitido", body: `<p>Puedes ver y compartir páginas públicas con fines legales, personales o de evaluación comercial. No interfieras con el sitio, intentes acceso no autorizado, introduzcas código dañino, extraigas contenido imponiendo una carga indebida, tergiverses nuestro contenido ni lo uses para infringir la ley.</p>`},
      {id: "intellectual-property", title: "4. Propiedad intelectual", body: `<p>Textos, diseño, logotipos, nombres de productos y contenido pertenecen a JAM Daily Tools LLC o sus licenciantes. No puedes reproducirlos o usarlos comercialmente sin permiso, salvo autorización legal. No se concede licencia de marca ni software.</p>`},
      {id: "third-party-links", title: "5. Enlaces de terceros", body: `<p>El sitio enlaza a productos, tiendas, correo y terceros. No controlamos su disponibilidad, contenido, seguridad, términos ni privacidad. Un enlace no implica respaldo de todas las afirmaciones u ofertas del destino.</p>`},
      {id: "warranty", title: "6. Exclusión de garantías", body: `<p>En la medida permitida, el sitio se ofrece “tal cual” y “según disponibilidad”. No garantizamos acceso continuo, ausencia de errores ni que las descripciones estén siempre actualizadas. No se excluye ninguna garantía o derecho obligatorio.</p>`},
      {id: "liability", title: "7. Limitación de responsabilidad", body: `<p>En la medida permitida, JAM Daily Tools LLC no responde por daños indirectos, incidentales, especiales, consecuentes, ejemplares o punitivos derivados del sitio. La limitación no se aplica a responsabilidad que legalmente no pueda limitarse.</p>`},
      {id: "mandatory-rights", title: "8. Derechos obligatorios", body: `<p>Nada limita derechos irrenunciables de Estados Unidos, Brasil, México, Canadá, Québec u otras leyes de consumo. Una norma local obligatoria prevalece solo en la medida necesaria.</p>`},
      {id: "governing-law", title: "9. Ley aplicable", body: `<p>Rige la ley de Texas, sin sus normas de conflicto, preservando la ley obligatoria de tu residencia. Los tribunales competentes del condado de Bexar, Texas, serán el foro donde la elección sea válida. No se exige arbitraje ni se renuncia a una acción colectiva legalmente disponible.</p>`},
      {id: "changes", title: "10. Cambios", body: `<p>Podemos actualizar estos Términos publicando nueva fecha y versión. Los cambios se aplican hacia el futuro. El uso posterior implica aceptación cuando la ley lo permita.</p>`},
      {id: "contact", title: "11. Contacto", body: `<address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>Estados Unidos</address><p>Correo: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>.</p>`},
    ],
  },
};
