export default {
  lang: "fr",
  prefix: "fr/",
  labels: {
    language: "Langue",
    primaryNavigation: "Navigation principale",
    footerNavigation: "Navigation de pied de page",
    products: "Produits",
    about: "À propos",
    privacy: "Confidentialité",
    terms: "Conditions",
    contact: "Nous joindre",
    home: "Accueil",
    rights: "Tous droits réservés.",
  },
  meta: {
    title: "JAM Daily Tools | Des applications pratiques au quotidien",
    description: "JAM Daily Tools LLC est un studio indépendant qui crée des applications ciblées pour le travail quotidien, dont TourneySmith pour les tournois de sports de raquette.",
  },
  landing: {
    heading: "Des logiciels ciblés pour<br><span class=\"grad\">le travail réel.</span>",
    lede: "Nous créons des applications claires et fiables pour les tâches récurrentes, à commencer par l’organisation de tournois.",
    viewApps: "Voir nos applications",
    getInTouch: "Communiquer avec nous",
    workTitle: "Notre méthode",
    workIntro: "Chaque produit part d’une tâche précise et reste concentré sur sa bonne exécution.",
    values: [
      {title: "Une utilité concrète", body: "Nous commençons par le travail que les gens doivent vraiment accomplir et retirons les étapes inutiles."},
      {title: "Des données expliquées", body: "Chaque produit indique ce qu’il recueille, pourquoi et quels contrôles sont disponibles."},
      {title: "Conçu pour les deux plateformes", body: "Nos produits mobiles sont pensés pour Android et iOS avec un comportement commun."},
    ],
    appsTitle: "Nos applications",
    appsIntro: "Le premier produit de JAM Daily Tools LLC.",
    comingSoon: "Bientôt disponible",
    productTagline: "L’art d’organiser des tournois.",
    productBody: "TourneySmith aide les organisateurs à choisir un format, gérer les joueurs et groupes, planifier les lieux et terrains, partager des invitations et regrouper tableaux en direct, scores, classements et résultats. Il prend en charge le padel, le tennis, le pickleball, le badminton, le squash, le racquetball et le tennis de table.",
    visitProduct: "Visiter TourneySmith",
    aboutBody: "JAM Daily Tools LLC est un studio de logiciels indépendant établi au Texas. Nous développons et publions des outils ciblés, en commençant par TourneySmith pour les organisateurs de tournois.",
    contactIntro: "Utilisez l’adresse qui correspond à votre question.",
    general: "Entreprise et affaires",
    appSupport: "Assistance produit",
  },
  privacy: {
    metaTitle: "Politique de confidentialité du site | JAM Daily Tools",
    metaDescription: "Politique du site de JAM Daily Tools sur les données techniques Cloudflare, la préférence linguistique, les courriels, la conservation et les demandes de confidentialité.",
    title: "Politique de confidentialité du site Web",
    updated: "Dernière mise à jour : 27 septembre 2026. Version du document : 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Portée", body: `<p>Cette politique couvre <strong>jamdailytools.com</strong>, le site public de JAM Daily Tools LLC. Il présente l’entreprise et ses produits, sans compte, formulaire de paiement ni base de données de produit.</p><p>Elle ne régit pas l’application TourneySmith, les invitations ou les données de compte. Ces éléments sont couverts par la <a data-product-link href="https://tourneysmith.com/fr/privacy">Politique de confidentialité de TourneySmith</a>.</p>`},
      {id: "controller", title: "2. Entreprise et coordonnées", body: `<p>JAM Daily Tools LLC est responsable des renseignements du site décrits ici.</p><address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>États-Unis</address><p>Confidentialité : <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Questions générales : <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>. Pour le Canada et le Québec, le titre responsable est <strong>Responsable de la protection des renseignements personnels</strong>.</p>`},
      {id: "website-data", title: "3. Données techniques du site", body: `<p>Nous n’ajoutons aucun script d’analyse, de publicité, de profilage ou de suivi social. Cloudflare traite automatiquement des données ordinaires comme l’adresse IP, le navigateur, l’appareil, le chemin demandé, l’heure, les signaux de sécurité et les journaux pour livrer les fichiers, acheminer le trafic et protéger le site.</p>`},
      {id: "language-preference", title: "4. Préférence linguistique", body: `<p>Lorsque vous choisissez une langue, le site enregistre <code>jam-language</code> dans votre navigateur. La page promotionnelle peut aussi utiliser la langue du navigateur pour suggérer une version. Les pages Confidentialité et Conditions ne changent jamais automatiquement de langue. Ce choix ne sert ni à l’analyse ni à la publicité et disparaît lorsque vous effacez les données du site.</p>`},
      {id: "email", title: "5. Si vous nous écrivez", body: `<p>Nous recevons votre adresse, votre message, les pièces jointes et les métadonnées de livraison. Nous les utilisons pour répondre, offrir l’assistance, conserver des dossiers appropriés, protéger nos systèmes et respecter la loi. N’envoyez aucun mot de passe ou document sensible sans méthode sécurisée.</p>`},
      {id: "cloudflare", title: "6. Fournisseur d’hébergement", body: `<p>Le site est livré par Cloudflare Workers Static Assets, le DNS et des services de sécurité. Cloudflare traite les données techniques selon ses modalités et sa politique. Les liens vers TourneySmith, les boutiques et d’autres tiers sont régis par leurs avis.</p>`},
      {id: "sharing", title: "7. Communication", body: `<p>Nous ne vendons pas les données des visiteurs et ne les partageons pas pour de la publicité ciblée. Nous pouvons transmettre la correspondance à nos fournisseurs de systèmes, à des conseillers sous confidentialité, aux autorités lorsque la loi l’exige ou lors d’une opération d’entreprise assortie de protections.</p>`},
      {id: "retention", title: "8. Conservation", body: `<p>La préférence reste jusqu’à sa modification ou l’effacement des données. Cloudflare conserve les dossiers techniques selon sa configuration et ses contrats. Nous gardons la correspondance seulement le temps nécessaire à la demande, à la sécurité, aux dossiers, aux différends et aux obligations légales, puis la supprimons ou l’anonymisons lorsque possible.</p>`},
      {id: "rights", title: "9. Choix et droits", body: `<p>Selon votre résidence, vous pouvez demander accès, correction, suppression, portabilité, limitation, opposition, information sur les destinataires ou retrait du consentement pour les renseignements détenus par JAM Daily Tools LLC. Écrivez à <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Nous pouvons vérifier votre identité. Vous pouvez aussi vous plaindre auprès de l’autorité compétente, notamment le Commissariat à la protection de la vie privée du Canada ou la Commission d’accès à l’information du Québec lorsqu’applicable.</p>`},
      {id: "children", title: "10. Enfants", body: `<p>Ce site d’entreprise ne vise pas les enfants et ne leur demande pas sciemment de renseignements. Avisez-nous si un enfant a envoyé des renseignements sans autorisation appropriée.</p>`},
      {id: "international", title: "11. Traitement international", body: `<p>JAM Daily Tools LLC est aux États-Unis. Cloudflare et les fournisseurs de courriel peuvent traiter les données techniques ou la correspondance aux États-Unis et ailleurs selon leurs modalités. Les règles varient. Les droits obligatoires du Canada, du Québec, du Brésil, du Mexique et d’autres lieux demeurent lorsqu’ils s’appliquent.</p>`},
      {id: "changes", title: "12. Modifications", body: `<p>Nous pouvons mettre cette politique à jour. Nous publierons la nouvelle date et version et fournirons un avis supplémentaire lorsque requis.</p>`},
      {id: "contact", title: "13. Nous joindre", body: `<p>Écrivez à <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a> ou à l’adresse de la section 2.</p>`},
    ],
  },
  terms: {
    metaTitle: "Conditions d’utilisation du site | JAM Daily Tools",
    metaDescription: "Conditions du site de JAM Daily Tools, avec une séparation claire entre ce site informatif et l’application et le service TourneySmith.",
    title: "Conditions d’utilisation du site Web",
    updated: "En vigueur et mises à jour le 27 septembre 2026. Version : 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Portée", body: `<p>Ces Conditions régissent l’utilisation de <strong>jamdailytools.com</strong>, site informatif de JAM Daily Tools LLC. En l’utilisant, vous les acceptez. Sinon, n’utilisez pas le site.</p>`},
      {id: "app-boundary", title: "2. Nos applications ont leurs propres conditions", body: `<p>Ces Conditions ne régissent pas les comptes, tournois, achats, invitations ou données de TourneySmith. Le produit possède ses propres <a data-product-link href="https://tourneysmith.com/fr/terms">Conditions d’utilisation</a> et sa <a data-product-link href="https://tourneysmith.com/fr/privacy">Politique de confidentialité</a>. Rien sur ce site d’entreprise ne les modifie.</p>`},
      {id: "site-use", title: "3. Utilisation permise", body: `<p>Vous pouvez consulter et partager les pages publiques à des fins légales, personnelles ou d’évaluation commerciale. N’interférez pas avec le site, ne tentez pas d’accès non autorisé, n’introduisez pas de code nuisible, ne l’extrayez pas d’une façon qui surcharge le service, ne dénaturez pas le contenu et ne l’utilisez pas pour enfreindre la loi.</p>`},
      {id: "intellectual-property", title: "4. Propriété intellectuelle", body: `<p>Les textes, la conception, les logos, les noms de produits et le contenu appartiennent à JAM Daily Tools LLC ou à ses concédants. Ne les reproduisez pas ou ne les exploitez pas commercialement sans autorisation, sauf permission légale. Aucune licence de marque ou logiciel n’est accordée.</p>`},
      {id: "third-party-links", title: "5. Liens de tiers", body: `<p>Le site mène vers des produits, boutiques, services de courriel et tiers. Nous ne contrôlons pas leur disponibilité, contenu, sécurité, conditions ou confidentialité. Un lien n’approuve pas toutes les déclarations ou offres de la destination.</p>`},
      {id: "warranty", title: "6. Exclusion", body: `<p>Dans la mesure permise, le site est fourni « tel quel » et « selon sa disponibilité ». Nous ne garantissons pas un accès continu, l’absence d’erreurs ou des descriptions toujours à jour. Aucune garantie ou protection obligatoire n’est exclue.</p>`},
      {id: "liability", title: "7. Limitation de responsabilité", body: `<p>Dans la mesure permise, JAM Daily Tools LLC n’est pas responsable des pertes indirectes, accessoires, spéciales, consécutives, exemplaires ou punitives liées au site. Cette limite ne vise pas une responsabilité qui ne peut légalement être limitée.</p>`},
      {id: "mandatory-rights", title: "8. Droits obligatoires", body: `<p>Rien ne limite les droits non renonçables des États-Unis, du Brésil, du Mexique, du Canada, du Québec ou d’autres lois de consommation. Une règle locale impérative prévaut seulement dans la mesure nécessaire.</p>`},
      {id: "governing-law", title: "9. Droit applicable", body: `<p>Le droit du Texas régit ces Conditions, sans ses règles de conflit, sous réserve du droit impératif de votre résidence. Les tribunaux compétents du comté de Bexar, Texas, constituent le for lorsque ce choix est valide. Aucun arbitrage n’est imposé et aucune action collective légalement disponible n’est abandonnée.</p>`},
      {id: "changes", title: "10. Modifications", body: `<p>Nous pouvons mettre ces Conditions à jour en publiant une nouvelle date et version. Les changements valent pour l’avenir. L’utilisation ultérieure constitue une acceptation lorsque la loi le permet.</p>`},
      {id: "contact", title: "11. Nous joindre", body: `<address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>États-Unis</address><p>Courriel : <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>.</p>`},
    ],
  },
};
