export default {
  lang: "it",
  prefix: "it/",
  labels: {
    language: "Lingua",
    primaryNavigation: "Navigazione principale",
    footerNavigation: "Navigazione a piè di pagina",
    products: "Prodotti",
    about: "Chi siamo",
    privacy: "Privacy",
    terms: "Termini",
    contact: "Contatti",
    home: "Home page",
    rights: "Tutti i diritti riservati.",
  },
  meta: {
    title: "JAM Daily Tools | Applicazioni pratiche per il lavoro quotidiano",
    description: "JAM Daily Tools LLC è uno studio indipendente che crea applicazioni mirate per il lavoro quotidiano, tra cui TourneySmith per i tornei di sport con racchetta.",
  },
  landing: {
    heading: "Software mirato per<br><span class=\"grad\">il lavoro reale.</span>",
    lede: "Creiamo applicazioni chiare e affidabili per attività ricorrenti, a partire dall’organizzazione dei tornei.",
    viewApps: "Vedi le applicazioni",
    getInTouch: "Contattaci",
    workTitle: "Come lavoriamo",
    workIntro: "Ogni prodotto parte da un compito preciso e resta concentrato sul farlo bene.",
    values: [
      {title: "Utile per scelta", body: "Partiamo dal lavoro che le persone devono davvero completare ed eliminiamo i passaggi inutili."},
      {title: "Dati spiegati chiaramente", body: "Ogni prodotto indica cosa raccoglie, perché ne ha bisogno e quali controlli offre."},
      {title: "Creato per entrambe le piattaforme", body: "I nostri prodotti mobili sono progettati per Android e iOS con comportamento condiviso."},
    ],
    appsTitle: "Le nostre applicazioni",
    appsIntro: "Il primo prodotto di JAM Daily Tools LLC.",
    comingSoon: "Prossimamente",
    productTagline: "L’arte di organizzare tornei.",
    productBody: "TourneySmith aiuta gli organizzatori a scegliere il formato, gestire giocatori e gruppi, programmare sedi e campi, condividere inviti e riunire tabelloni in tempo reale, punteggi, classifiche e risultati. Supporta padel, tennis, pickleball, badminton, squash, racquetball e tennistavolo.",
    visitProduct: "Visita TourneySmith",
    aboutBody: "JAM Daily Tools LLC è uno studio di software indipendente con sede in Texas. Sviluppiamo e pubblichiamo strumenti mirati, a partire da TourneySmith per gli organizzatori di tornei.",
    contactIntro: "Usa l’indirizzo adatto alla tua domanda.",
    general: "Azienda e affari",
    appSupport: "Assistenza prodotto",
  },
  privacy: {
    metaTitle: "Informativa privacy del sito | JAM Daily Tools",
    metaDescription: "Informativa del sito aziendale JAM Daily Tools su dati tecnici Cloudflare, preferenza linguistica, e-mail, conservazione e richieste privacy.",
    title: "Informativa sulla privacy del sito",
    updated: "Ultimo aggiornamento: 27 settembre 2026. Versione del documento: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Ambito", body: `<p>Questa informativa riguarda <strong>jamdailytools.com</strong>, il sito aziendale pubblico di JAM Daily Tools LLC. Presenta azienda e prodotti e non contiene account, pagamenti o database di prodotto.</p><p>Non regola l’app TourneySmith, gli inviti o i dati degli account. Questi aspetti sono descritti nell’<a data-product-link href="https://tourneysmith.com/it/privacy">Informativa sulla privacy di TourneySmith</a>.</p>`},
      {id: "controller", title: "2. Azienda e contatti", body: `<p>JAM Daily Tools LLC è responsabile delle informazioni del sito descritte qui.</p><address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>Stati Uniti</address><p>Privacy: <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Domande generali: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>. Per Canada e Québec, il ruolo responsabile è <strong>Responsabile della privacy</strong>.</p>`},
      {id: "website-data", title: "3. Dati tecnici del sito", body: `<p>Non aggiungiamo script di analisi, pubblicità, profilazione o tracciamento sociale. Cloudflare tratta automaticamente dati comuni come IP, browser, dispositivo, percorso richiesto, orario, segnali di sicurezza e log per distribuire i file, instradare il traffico e proteggere il sito.</p>`},
      {id: "language-preference", title: "4. Preferenza linguistica", body: `<p>Quando scegli una lingua, il sito salva <code>jam-language</code> nel browser. La pagina promozionale può anche usare la lingua del browser per suggerire una versione. Le pagine Privacy e Termini non cambiano mai automaticamente lingua. La preferenza non serve per analisi o pubblicità e può essere rimossa cancellando i dati del sito.</p>`},
      {id: "email", title: "5. Se ci scrivi", body: `<p>Riceviamo indirizzo, messaggio, allegati e metadati di consegna. Li usiamo per rispondere, fornire assistenza, tenere registri aziendali appropriati, proteggere i sistemi e rispettare la legge. Non inviare password o documenti sensibili senza un metodo sicuro.</p>`},
      {id: "cloudflare", title: "6. Fornitore di hosting", body: `<p>Il sito è distribuito tramite Cloudflare Workers Static Assets, DNS e servizi di sicurezza. Cloudflare tratta dati tecnici secondo i propri termini e la propria informativa. I link a TourneySmith, store e terze parti seguono gli avvisi di quei siti.</p>`},
      {id: "sharing", title: "7. Condivisione", body: `<p>Non vendiamo dati dei visitatori e non li condividiamo per pubblicità mirata. Possiamo comunicare la corrispondenza a fornitori dei nostri sistemi, consulenti soggetti a riservatezza, autorità quando richiesto o nell’ambito di un’operazione societaria con adeguate protezioni.</p>`},
      {id: "retention", title: "8. Conservazione", body: `<p>La preferenza resta finché non la modifichi o cancelli i dati. Cloudflare conserva i registri tecnici secondo configurazione e contratti. Manteniamo la corrispondenza solo per il tempo necessario alla richiesta, sicurezza, registri, controversie e obblighi legali, poi la eliminiamo o anonimizziamo quando possibile.</p>`},
      {id: "rights", title: "9. Scelte e diritti", body: `<p>In base alla residenza, puoi chiedere accesso, correzione, eliminazione, portabilità, limitazione, opposizione, informazioni sui destinatari o revoca del consenso per dati detenuti da JAM Daily Tools LLC. Scrivi a <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Possiamo verificare l’identità. Puoi anche presentare reclamo all’autorità competente, compreso l’Office of the Privacy Commissioner of Canada o la Commission d’accès à l’information del Québec quando applicabile.</p>`},
      {id: "children", title: "10. Minori", body: `<p>Questo sito aziendale non è rivolto ai minori e non richiede intenzionalmente i loro dati. Avvisaci se ritieni che un minore abbia inviato informazioni senza autorizzazione adeguata.</p>`},
      {id: "international", title: "11. Trattamento internazionale", body: `<p>JAM Daily Tools LLC è negli Stati Uniti. Cloudflare e i fornitori e-mail possono trattare dati tecnici o corrispondenza negli Stati Uniti e altrove secondo i loro termini. Le regole variano. I diritti obbligatori di Canada, Québec, Brasile, Messico e altri luoghi restano quando applicabili.</p>`},
      {id: "changes", title: "12. Modifiche", body: `<p>Possiamo aggiornare questa informativa. Pubblicheremo nuova data e versione e daremo ulteriore avviso quando richiesto.</p>`},
      {id: "contact", title: "13. Contatti", body: `<p>Scrivi a <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a> o all’indirizzo della sezione 2.</p>`},
    ],
  },
  terms: {
    metaTitle: "Termini d’uso del sito | JAM Daily Tools",
    metaDescription: "Termini del sito aziendale JAM Daily Tools, con una separazione chiara tra questo sito informativo e l’app e il servizio TourneySmith.",
    title: "Termini d’uso del sito",
    updated: "In vigore e aggiornati il 27 settembre 2026. Versione: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Ambito", body: `<p>Questi Termini regolano l’uso di <strong>jamdailytools.com</strong>, il sito informativo di JAM Daily Tools LLC. Usandolo, li accetti. Se non accetti, non usare il sito.</p>`},
      {id: "app-boundary", title: "2. Le applicazioni hanno termini separati", body: `<p>Questi Termini non regolano account, tornei, acquisti, inviti o dati di TourneySmith. Il prodotto ha <a data-product-link href="https://tourneysmith.com/it/terms">Termini di servizio</a> e <a data-product-link href="https://tourneysmith.com/it/privacy">Informativa sulla privacy</a> propri. Nulla in questo sito aziendale li modifica.</p>`},
      {id: "site-use", title: "3. Uso consentito", body: `<p>Puoi consultare e condividere pagine pubbliche per scopi legali, personali o di valutazione commerciale. Non interferire, tentare accessi non autorizzati, introdurre codice dannoso, estrarre contenuti sovraccaricando il servizio, travisare il contenuto o usare il sito per violare la legge.</p>`},
      {id: "intellectual-property", title: "4. Proprietà intellettuale", body: `<p>Testi, design, loghi, nomi di prodotti e contenuti appartengono a JAM Daily Tools LLC o ai licenzianti. Non riprodurli o usarli commercialmente senza permesso, salvo autorizzazione legale. Non è concessa alcuna licenza di marchio o software.</p>`},
      {id: "third-party-links", title: "5. Link di terze parti", body: `<p>Il sito rimanda a prodotti, store, e-mail e terze parti. Non controlliamo disponibilità, contenuto, sicurezza, termini o privacy. Un link non approva tutte le affermazioni o offerte della destinazione.</p>`},
      {id: "warranty", title: "6. Esclusione", body: `<p>Nella massima misura consentita, il sito è fornito “così com’è” e “secondo disponibilità”. Non garantiamo accesso continuo, assenza di errori o descrizioni sempre aggiornate. Nessuna garanzia o tutela obbligatoria è esclusa.</p>`},
      {id: "liability", title: "7. Limitazione di responsabilità", body: `<p>Nella massima misura consentita, JAM Daily Tools LLC non risponde di perdite indirette, incidentali, speciali, consequenziali, esemplari o punitive derivanti dal sito. Il limite non si applica a responsabilità che non può essere limitata per legge.</p>`},
      {id: "mandatory-rights", title: "8. Diritti obbligatori", body: `<p>Nulla limita diritti inderogabili degli Stati Uniti, Brasile, Messico, Canada, Québec o altre leggi dei consumatori. Una norma locale obbligatoria prevale solo nella misura necessaria.</p>`},
      {id: "governing-law", title: "9. Legge applicabile", body: `<p>La legge del Texas regola questi Termini, escluse le norme di conflitto, preservando le norme obbligatorie della tua residenza. I tribunali competenti della contea di Bexar, Texas, sono il foro dove valido. Non è imposto arbitrato e non si rinuncia ad azioni collettive legalmente disponibili.</p>`},
      {id: "changes", title: "10. Modifiche", body: `<p>Possiamo aggiornare questi Termini pubblicando nuova data e versione. Le modifiche valgono per il futuro. L’uso successivo costituisce accettazione dove consentito.</p>`},
      {id: "contact", title: "11. Contatti", body: `<address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>Stati Uniti</address><p>E-mail: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>.</p>`},
    ],
  },
};
