export default {
  lang: "pt-BR",
  prefix: "pt/",
  labels: {
    language: "Idioma",
    primaryNavigation: "Navegação principal",
    footerNavigation: "Navegação do rodapé",
    products: "Produtos",
    about: "Sobre",
    privacy: "Privacidade",
    terms: "Termos",
    contact: "Contato",
    home: "Início",
    rights: "Todos os direitos reservados.",
  },
  meta: {
    title: "JAM Daily Tools | Aplicativos práticos para o dia a dia",
    description: "A JAM Daily Tools LLC é um estúdio independente que cria aplicativos focados em tarefas cotidianas, incluindo o TourneySmith para torneios de esportes de raquete.",
  },
  landing: {
    heading: "Software focado para<br><span class=\"grad\">trabalho de verdade.</span>",
    lede: "Criamos aplicativos claros e confiáveis para tarefas recorrentes, começando pela organização de torneios.",
    viewApps: "Ver aplicativos",
    getInTouch: "Fale conosco",
    workTitle: "Como trabalhamos",
    workIntro: "Cada produto começa com uma tarefa específica e permanece focado em executá-la bem.",
    values: [
      {title: "Útil desde o projeto", body: "Começamos pelo trabalho que as pessoas realmente precisam concluir e removemos etapas que não ajudam."},
      {title: "Clareza sobre dados", body: "Cada produto explica o que coleta, por que precisa e quais controles oferece."},
      {title: "Feito para as duas plataformas", body: "Nossos produtos móveis são projetados para Android e iOS com comportamento compartilhado."},
    ],
    appsTitle: "Nossos aplicativos",
    appsIntro: "O primeiro produto da JAM Daily Tools LLC.",
    comingSoon: "Em breve",
    productTagline: "A arte de organizar torneios.",
    productBody: "O TourneySmith ajuda organizadores de esportes de raquete a escolher formatos, gerenciar jogadores e grupos, programar locais e quadras, compartilhar convites e reunir chaves ao vivo, placares, classificação e resultados. Ele oferece padel, tênis, pickleball, badminton, squash, raquetebol e tênis de mesa.",
    visitProduct: "Visitar o TourneySmith",
    aboutBody: "A JAM Daily Tools LLC é um estúdio de software independente sediado no Texas. Desenvolvemos e publicamos ferramentas focadas, começando pelo TourneySmith para organizadores de torneios.",
    contactIntro: "Use o endereço adequado para sua pergunta.",
    general: "Empresa e negócios",
    appSupport: "Suporte do produto",
  },
  privacy: {
    metaTitle: "Política de Privacidade do Site | JAM Daily Tools",
    metaDescription: "Política do site corporativo da JAM Daily Tools sobre dados técnicos da Cloudflare, preferência de idioma, mensagens de e-mail, retenção e solicitações de privacidade.",
    title: "Política de Privacidade do Site",
    updated: "Última atualização: 27 de setembro de 2026. Versão do documento: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Escopo", body: `<p>Esta política abrange <strong>jamdailytools.com</strong>, o site corporativo público da JAM Daily Tools LLC. Ele apresenta a empresa e os produtos e não possui contas, pagamento ou banco de dados de produto.</p><p>Ela não rege o aplicativo TourneySmith, convites nem dados das contas. Esses assuntos estão na <a data-product-link href="https://tourneysmith.com/pt/privacy">Política de Privacidade do TourneySmith</a>.</p>`},
      {id: "controller", title: "2. Empresa e contato", body: `<p>A JAM Daily Tools LLC é responsável pelas informações do site descritas aqui.</p><address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>Estados Unidos</address><p>Privacidade: <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Assuntos gerais: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>. Para Canadá e Québec, o cargo responsável é <strong>Responsável pela Privacidade</strong>.</p>`},
      {id: "website-data", title: "3. Dados técnicos do site", body: `<p>Não adicionamos scripts de análise, publicidade, criação de perfil ou rastreamento social. A Cloudflare processa automaticamente dados comuns como IP, navegador, dispositivo, caminho solicitado, horário, sinais de segurança e logs para entregar os arquivos, rotear tráfego e proteger o site.</p>`},
      {id: "language-preference", title: "4. Preferência de idioma", body: `<p>Ao escolher um idioma, o site guarda <code>jam-language</code> no navegador. A página promocional também pode usar o idioma do navegador para sugerir uma versão. As páginas de Privacidade e Termos nunca mudam automaticamente. A preferência não serve para análise ou publicidade e pode ser removida ao limpar os dados do site.</p>`},
      {id: "email", title: "5. Se você enviar um e-mail", body: `<p>Recebemos seu endereço, mensagem, anexos e metadados de entrega. Usamos para responder, prestar suporte, manter registros empresariais adequados, proteger sistemas e cumprir a lei. Não envie senhas ou documentos sensíveis sem um método seguro.</p>`},
      {id: "cloudflare", title: "6. Provedor de hospedagem", body: `<p>O site é entregue por Cloudflare Workers Static Assets, DNS e serviços de segurança. A Cloudflare trata dados técnicos conforme seus termos e política. Links para o TourneySmith, lojas e terceiros seguem os avisos desses sites.</p>`},
      {id: "sharing", title: "7. Compartilhamento", body: `<p>Não vendemos dados de visitantes nem os compartilhamos para publicidade direcionada. Podemos compartilhar correspondência com provedores de sistemas, consultores sob confidencialidade, autoridades quando exigido ou em operação societária com proteções adequadas.</p>`},
      {id: "retention", title: "8. Retenção", body: `<p>A preferência fica até você alterá-la ou limpar os dados. A Cloudflare mantém registros técnicos segundo sua configuração e contratos. Guardamos correspondência somente pelo tempo necessário à consulta, segurança, registros, controvérsias e obrigações legais e depois a eliminamos ou anonimizamos quando viável.</p>`},
      {id: "rights", title: "9. Escolhas e direitos", body: `<p>Conforme seu local, você pode pedir acesso, correção, exclusão, portabilidade, restrição, oposição, informação sobre destinatários ou retirada de consentimento para dados mantidos pela JAM Daily Tools LLC. Escreva a <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a>. Podemos verificar sua identidade. Você também pode reclamar à autoridade competente, incluindo o Office of the Privacy Commissioner of Canada ou a Commission d’accès à l’information do Québec quando aplicável.</p>`},
      {id: "children", title: "10. Crianças", body: `<p>Este site corporativo não é dirigido a crianças e não solicita intencionalmente seus dados. Avise se acreditar que uma criança enviou informações sem autorização adequada.</p>`},
      {id: "international", title: "11. Processamento internacional", body: `<p>A JAM Daily Tools LLC fica nos Estados Unidos. Cloudflare e provedores de e-mail podem tratar dados técnicos ou correspondência nos Estados Unidos e outros países sob seus termos. As regras variam. Direitos obrigatórios do Canadá, Québec, Brasil, México e outros locais permanecem quando aplicáveis.</p>`},
      {id: "changes", title: "12. Alterações", body: `<p>Podemos atualizar esta política. Publicaremos nova data e versão e daremos aviso adicional quando exigido.</p>`},
      {id: "contact", title: "13. Contato", body: `<p>Escreva para <a href="mailto:privacy@jamdailytools.com">privacy@jamdailytools.com</a> ou para o endereço da seção 2.</p>`},
    ],
  },
  terms: {
    metaTitle: "Termos de Uso do Site | JAM Daily Tools",
    metaDescription: "Termos para usar o site corporativo da JAM Daily Tools, com separação clara entre este site informativo e o aplicativo e serviço TourneySmith.",
    title: "Termos de Uso do Site",
    updated: "Vigentes e atualizados em 27 de setembro de 2026. Versão: 2026-09-27.",
    sections: [
      {id: "scope", title: "1. Escopo", body: `<p>Estes Termos regem o uso de <strong>jamdailytools.com</strong>, o site informativo da JAM Daily Tools LLC. Ao usar, você concorda. Se não concordar, não use o site.</p>`},
      {id: "app-boundary", title: "2. Nossos aplicativos têm termos próprios", body: `<p>Estes Termos não regem contas, torneios, compras, convites ou dados do TourneySmith. O produto tem <a data-product-link href="https://tourneysmith.com/pt/terms">Termos de Serviço</a> e <a data-product-link href="https://tourneysmith.com/pt/privacy">Política de Privacidade</a> próprios. Nada neste site corporativo altera esses documentos.</p>`},
      {id: "site-use", title: "3. Uso permitido", body: `<p>Você pode consultar e compartilhar páginas públicas para fins legais, pessoais ou de avaliação comercial. Não interfira, tente acesso indevido, introduza código malicioso, faça coleta que sobrecarregue o serviço, deturpe o conteúdo ou use o site para infringir a lei.</p>`},
      {id: "intellectual-property", title: "4. Propriedade intelectual", body: `<p>Textos, design, logotipos, nomes e conteúdo pertencem à JAM Daily Tools LLC ou licenciantes. Não os reproduza ou use comercialmente sem permissão, salvo autorização legal. Nenhuma licença de marca ou software é concedida.</p>`},
      {id: "third-party-links", title: "5. Links de terceiros", body: `<p>O site aponta para produtos, lojas, e-mail e terceiros. Não controlamos disponibilidade, conteúdo, segurança, termos ou privacidade. Um link não endossa toda afirmação ou oferta do destino.</p>`},
      {id: "warranty", title: "6. Isenção", body: `<p>Na máxima medida legal, o site é fornecido “no estado em que se encontra” e “conforme disponível”. Não garantimos acesso ininterrupto, ausência de erros ou descrições sempre atuais. Nenhuma garantia ou direito obrigatório é excluído.</p>`},
      {id: "liability", title: "7. Limitação de responsabilidade", body: `<p>Na máxima medida permitida, a JAM Daily Tools LLC não responde por perdas indiretas, incidentais, especiais, consequenciais, exemplares ou punitivas decorrentes do site. O limite não se aplica ao que legalmente não pode ser limitado.</p>`},
      {id: "mandatory-rights", title: "8. Direitos obrigatórios", body: `<p>Nada limita direitos irrenunciáveis dos Estados Unidos, Brasil, México, Canadá, Québec ou outras leis de consumo. Norma local obrigatória prevalece apenas na medida necessária.</p>`},
      {id: "governing-law", title: "9. Lei aplicável", body: `<p>A lei do Texas rege estes Termos, sem regras de conflito, preservadas as normas obrigatórias da sua residência. Tribunais competentes do condado de Bexar, Texas, são o foro onde válido. Não há arbitragem obrigatória nem renúncia a ação coletiva legalmente disponível.</p>`},
      {id: "changes", title: "10. Alterações", body: `<p>Podemos atualizar estes Termos publicando nova data e versão. Mudanças valem para o futuro. O uso posterior representa aceitação onde permitido.</p>`},
      {id: "contact", title: "11. Contato", body: `<address>JAM Daily Tools LLC<br>18203 Rim Drive 101 #1120<br>San Antonio, TX 78257<br>Estados Unidos</address><p>E-mail: <a href="mailto:admin@jamdailytools.com">admin@jamdailytools.com</a>.</p>`},
    ],
  },
};
